---
- name: Install kuberenetes packages on all hosts
  hosts: all
  tasks:

    - name: add apt signing key for kubernetes (1/4)
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: adding apt repository for kubernetes (2/4)
      apt_repository:
        repo: deb http://packages.cloud.google.com/apt/ kubernetes-xenial main
        state: present
      register: kubernetes_repository
      retries: 10
      until: kubernetes_repository is success

    - name: Copy k8s.conf file to servers
      copy:
        src: ./k8s.conf
        dest: /etc/sysctl.d/

    - name: Copy docker custom daeom file to servers
      copy:
        src: ./daemon.json
        dest: /etc/docker/

    - name: Create a directory if it does not exist
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Installing kubeadm, kubelet and kubectl
      package:
        name: 
          - kubelet 
          - kubeadm 
          - kubectl
        state: latest
        
    - name: Restart & enable kubelet service
      service:
        name: kubelet
        state: restarted
        enabled: yes

    - name: Restart & enable docker service
      service:
        name: docker
        state: restarted
        enabled: yes

